"""
Drawing border and title block for SLD drawings.
Standard A3 landscape (420mm x 297mm).
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.sld.backend import DrawingBackend


def draw_border(backend: DrawingBackend, margin: float = 10) -> None:
    """Draw the drawing border rectangle."""
    w = 420 - margin
    h = 297 - margin
    backend.set_layer("SLD_TITLE_BLOCK")
    backend.add_lwpolyline(
        [(margin, margin), (w, margin), (w, h), (margin, h)],
        close=True,
    )


def draw_title_block(
    backend: DrawingBackend,
    project_name: str = "Electrical Installation",
    address: str = "",
    postal_code: str = "",
    kva: int = 0,
    drawing_number: str = "SLD-001",
    lew_name: str = "",
    lew_licence: str = "",
    revision: str = "A",
    sld_only_mode: bool = False,
) -> None:
    """
    Draw the title block in the bottom-right corner.
    Standard engineering drawing title block layout.
    """
    # Title block area
    tb_left = 260
    tb_right = 410
    tb_bottom = 10
    tb_top = 55
    tb_mid_y = (tb_top + tb_bottom) / 2

    backend.set_layer("SLD_TITLE_BLOCK")

    # Outer box
    backend.add_lwpolyline(
        [(tb_left, tb_bottom), (tb_right, tb_bottom), (tb_right, tb_top), (tb_left, tb_top)],
        close=True,
    )

    # Horizontal dividers
    backend.add_line((tb_left, tb_mid_y), (tb_right, tb_mid_y))
    backend.add_line((tb_left, tb_mid_y - 10), (tb_right, tb_mid_y - 10))

    # Vertical divider in top row
    mid_x = (tb_left + tb_right) / 2
    backend.add_line((mid_x, tb_mid_y), (mid_x, tb_top))

    # ── Text content ──────────────────────────────────

    # Title
    backend.set_layer("SLD_ANNOTATIONS")
    backend.add_mtext(
        "SINGLE LINE DIAGRAM",
        insert=(tb_left + 5, tb_top - 3),
        char_height=4,
    )

    # Project name
    backend.add_mtext(
        f"Project: {project_name}",
        insert=(tb_left + 5, tb_top - 10),
        char_height=3,
    )

    # Address
    if address:
        addr_text = address
        if postal_code:
            addr_text += f"\\PSingapore {postal_code}"
        backend.add_mtext(
            addr_text,
            insert=(tb_left + 5, tb_top - 16),
            char_height=2.5,
        )

    # Capacity
    if kva:
        backend.add_mtext(
            f"Capacity: {kva} kVA",
            insert=(mid_x + 5, tb_top - 3),
            char_height=3,
        )

    # Drawing number
    backend.add_mtext(
        f"Drawing No: {drawing_number}",
        insert=(mid_x + 5, tb_top - 10),
        char_height=3,
    )

    # Revision and date
    backend.add_mtext(
        f"Rev: {revision}  Date: {date.today().isoformat()}",
        insert=(mid_x + 5, tb_top - 16),
        char_height=2.5,
    )

    # LEW information (bottom row)
    if sld_only_mode:
        # SLD 전용 모드: "Prepared by" 섹션을 비워둠 — 사용자가 인쇄 후 직접 기입
        backend.add_mtext(
            "Prepared by: (To be filled by LEW)",
            insert=(tb_left + 5, tb_mid_y - 3),
            char_height=2.5,
        )
        backend.add_mtext(
            "LEW: ____________________",
            insert=(tb_left + 5, tb_mid_y - 8),
            char_height=3,
        )
        backend.add_mtext(
            "Licence No: ____________________",
            insert=(tb_left + 5, tb_mid_y - 14),
            char_height=2.5,
        )
    else:
        backend.add_mtext(
            "Prepared by:",
            insert=(tb_left + 5, tb_mid_y - 3),
            char_height=2.5,
        )

        if lew_name:
            backend.add_mtext(
                f"LEW: {lew_name}",
                insert=(tb_left + 5, tb_mid_y - 8),
                char_height=3,
            )

        if lew_licence:
            backend.add_mtext(
                f"Licence No: {lew_licence}",
                insert=(tb_left + 5, tb_mid_y - 14),
                char_height=2.5,
            )

    # AI-generated notice
    backend.add_mtext(
        "Generated by LicenseKaki AI — Verify before submission",
        insert=(tb_left + 5, tb_bottom + 3),
        char_height=2,
    )
