"""
Drawing border and title block for SLD drawings.
Standard A3 landscape (420mm x 297mm).
"""

import ezdxf
from ezdxf.layouts import Modelspace
from datetime import date


def draw_border(msp: Modelspace, margin: float = 10) -> None:
    """Draw the drawing border rectangle."""
    w = 420 - margin
    h = 297 - margin
    msp.add_lwpolyline(
        [(margin, margin), (w, margin), (w, h), (margin, h)],
        close=True,
        dxfattribs={"layer": "SLD_TITLE_BLOCK"},
    )


def draw_title_block(
    msp: Modelspace,
    project_name: str = "Electrical Installation",
    address: str = "",
    postal_code: str = "",
    kva: int = 0,
    drawing_number: str = "SLD-001",
    lew_name: str = "",
    lew_licence: str = "",
    revision: str = "A",
) -> None:
    """
    Draw the title block in the bottom-right corner.
    Standard engineering drawing title block layout.
    """
    # Title block area
    tb_left = 260
    tb_right = 410
    tb_bottom = 10
    tb_top = 55
    tb_mid_y = (tb_top + tb_bottom) / 2

    attribs = {"layer": "SLD_TITLE_BLOCK"}

    # Outer box
    msp.add_lwpolyline(
        [(tb_left, tb_bottom), (tb_right, tb_bottom), (tb_right, tb_top), (tb_left, tb_top)],
        close=True,
        dxfattribs=attribs,
    )

    # Horizontal dividers
    msp.add_line((tb_left, tb_mid_y), (tb_right, tb_mid_y), dxfattribs=attribs)
    msp.add_line((tb_left, tb_mid_y - 10), (tb_right, tb_mid_y - 10), dxfattribs=attribs)

    # Vertical divider in top row
    mid_x = (tb_left + tb_right) / 2
    msp.add_line((mid_x, tb_mid_y), (mid_x, tb_top), dxfattribs=attribs)

    text_attribs = {"layer": "SLD_ANNOTATIONS", "char_height": 3}

    # Title
    msp.add_mtext(
        "SINGLE LINE DIAGRAM",
        dxfattribs={**text_attribs, "char_height": 4, "insert": (tb_left + 5, tb_top - 3)},
    )

    # Project name
    msp.add_mtext(
        f"Project: {project_name}",
        dxfattribs={**text_attribs, "insert": (tb_left + 5, tb_top - 10)},
    )

    # Address
    if address:
        addr_text = address
        if postal_code:
            addr_text += f"\\PSingapore {postal_code}"
        msp.add_mtext(
            addr_text,
            dxfattribs={**text_attribs, "char_height": 2.5, "insert": (tb_left + 5, tb_top - 16)},
        )

    # Capacity
    if kva:
        msp.add_mtext(
            f"Capacity: {kva} kVA",
            dxfattribs={**text_attribs, "insert": (mid_x + 5, tb_top - 3)},
        )

    # Drawing number
    msp.add_mtext(
        f"Drawing No: {drawing_number}",
        dxfattribs={**text_attribs, "insert": (mid_x + 5, tb_top - 10)},
    )

    # Revision and date
    msp.add_mtext(
        f"Rev: {revision}  Date: {date.today().isoformat()}",
        dxfattribs={**text_attribs, "char_height": 2.5, "insert": (mid_x + 5, tb_top - 16)},
    )

    # LEW information (bottom row)
    msp.add_mtext(
        "Prepared by:",
        dxfattribs={**text_attribs, "char_height": 2.5, "insert": (tb_left + 5, tb_mid_y - 3)},
    )

    if lew_name:
        msp.add_mtext(
            f"LEW: {lew_name}",
            dxfattribs={**text_attribs, "insert": (tb_left + 5, tb_mid_y - 8)},
        )

    if lew_licence:
        msp.add_mtext(
            f"Licence No: {lew_licence}",
            dxfattribs={**text_attribs, "char_height": 2.5, "insert": (tb_left + 5, tb_mid_y - 14)},
        )

    # AI-generated notice
    msp.add_mtext(
        "Generated by LicenseKaki AI — Verify before submission",
        dxfattribs={
            "layer": "SLD_ANNOTATIONS",
            "char_height": 2,
            "insert": (tb_left + 5, tb_bottom + 3),
        },
    )
