package com.bluelight.backend.domain.audit;

/**
 * 감사 로그 액션 유형
 */
public enum AuditAction {
    // Auth
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    SIGNUP,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,
    EMAIL_VERIFIED,

    // Application lifecycle
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_STATUS_CHANGE,
    APPLICATION_REVISION_REQUESTED,
    APPLICATION_APPROVED,
    APPLICATION_COMPLETED,
    APPLICATION_RESUBMITTED,

    // File
    FILE_UPLOADED,
    FILE_DELETED,

    // Document Request (Phase 2)
    DOCUMENT_UPLOADED_VOLUNTARY,
    DOCUMENT_DELETED_VOLUNTARY,

    // Document Request — LEW 워크플로 (Phase 3 PR#1)
    DOCUMENT_REQUEST_CREATED,
    DOCUMENT_REQUEST_FULFILLED,
    DOCUMENT_REQUEST_APPROVED,
    DOCUMENT_REQUEST_REJECTED,
    DOCUMENT_REQUEST_CANCELLED,

    // LOA snapshot (Phase 2 PR#4)
    LOA_SNAPSHOT_CREATED,

    // Admin user management
    LEW_APPROVED,
    LEW_REJECTED,
    USER_ROLE_CHANGED,

    // Admin application management
    PAYMENT_CONFIRMED,
    LEW_ASSIGNED,
    LEW_UNASSIGNED,

    // System settings
    SYSTEM_PROMPT_UPDATED,
    SYSTEM_PROMPT_RESET,
    SLD_SYSTEM_PROMPT_UPDATED,
    SLD_SYSTEM_PROMPT_RESET,
    GEMINI_KEY_UPDATED,
    GEMINI_KEY_CLEARED,
    EMAIL_VERIFICATION_TOGGLED,
    SLD_AI_GENERATION_TOGGLED,
    PRICE_UPDATED,
    SETTINGS_UPDATED,

    // PDPA data rights
    DATA_EXPORTED,
    ACCOUNT_DELETED,
    PDPA_CONSENT_WITHDRAWN,
    PROFILE_COMPANY_INFO_UPDATED,
    CORPORATE_INFO_CAPTURED_VIA_JIT,

    // Phase 5: kVA 확정 (security-review §4 — 3종 분리)
    KVA_CONFIRMED_BY_LEW,
    KVA_OVERRIDDEN_BY_ADMIN,
    KVA_CONFIRMATION_DENIED,

    // Data breach
    DATA_BREACH_REPORTED,
    DATA_BREACH_PDPC_NOTIFIED,
    DATA_BREACH_USERS_NOTIFIED,
    DATA_BREACH_RESOLVED,

    // Phase 1 — Kaki Concierge Service (v1.5)
    CONCIERGE_REQUEST_SUBMITTED,
    CONCIERGE_ACCOUNT_AUTO_CREATED,
    CONCIERGE_EXISTING_USER_LINKED,
    CONCIERGE_MANAGER_ASSIGNED,
    CONCIERGE_STATUS_TRANSITION,
    CONCIERGE_NOTE_ADDED,
    CONCIERGE_CANCELLED,
    USER_CONSENT_RECORDED,
    ACCOUNT_SETUP_TOKEN_ISSUED,
    ACCOUNT_SETUP_TOKEN_FAILED_ATTEMPT,    // H-3
    ACCOUNT_SETUP_TOKEN_LOCKED,            // H-3
    ACCOUNT_ACTIVATED,
    ACCOUNT_ACTIVATION_REQUEST_SENT,       // H-1, §4.4 옵션 B
    ACCOUNT_ACTIVATION_REQUEST_NO_MATCH,   // H-1, 이메일 미존재도 동일 응답 (감사 내부 기록)
    APPLICATION_CREATED_ON_BEHALF,
    LOA_SIGNATURE_UPLOADED_BY_MANAGER,
    LOA_SIGNATURE_IMPLICIT_CONSENT_LAPSED, // O-15, 7일 이의 제기 창구 만료
    LOGIN_FAILED_UNKNOWN_EMAIL,            // v1.5 AC-29 관련
    LOGIN_FAILED_BAD_PASSWORD,             // v1.5 AC-29 관련
    LOGIN_FAILED_DELETED                   // v1.5 AC-29 관련
}
