"""Generate 63A TPN SLD from Excel schedule data — verify circuit ID fix."""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.sld.generator import SldGenerator

requirements = {
    "supply_type": "three_phase",
    "kva": 69.282,
    "voltage": 400,
    "main_breaker": {
        "type": "MCB",
        "rating": 63,
        "poles": "TPN",
        "fault_kA": 10,
        "breaker_characteristic": "B",
    },
    "elcb": {
        "type": "ELCB",
        "rating": 63,
        "sensitivity_ma": 30,
        "poles": 4,
    },
    "busbar_rating": 100,
    "metering": "sp_meter",
    "supply_source": "landlord",
    "incoming_cable": "4 x 16mm² 1C PVC/PVC CABLE + 16mm² CPC IN METAL TRUNKING",
    "meter_board": {
        "isolator_rating": 63,
        "isolator_type": "4P",
        "meter_type": "KWH",
        "outgoing_breaker": {
            "type": "MCB",
            "rating": 63,
            "poles": "TPN",
            "characteristic": "B",
            "fault_kA": 10,
        },
    },
    # 23 circuits from Excel — SPAREs auto-generated by _pad_spares_for_triplets()
    "sub_circuits": [
        # === Lighting (S) section — 7 circuits → auto-pad to 9 (2 SPAREs) ===
        {
            "name": "1 Nos LIGHTS",
            "circuit_id": "L1S1",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos LIGHTS + 1 Nos EMERGENCY CABINET LED",
            "circuit_id": "L2S1",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos EMERGENCY LIGHTS + 1 Nos EXIT LIGHT",
            "circuit_id": "L3S1",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "4 Nos LIGHTS + 1 Nos EMERGENCY CABINET LED",
            "circuit_id": "L1S2",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos LIGHTS + 2 Nos FANS + 1 Nos EMERGENCY CABINET LED",
            "circuit_id": "L2S2",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos LIGHTS + 1 Nos EMERGENCY CABINET LED",
            "circuit_id": "L3S2",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "11 Nos LIGHTS + COVE LED + EXIT LIGHT + 1 Nos SIGNAGE",
            "circuit_id": "L1S3",
            "breaker_type": "MCB",
            "breaker_rating": 10,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 1.5mm² PVC + 1.5mm² CPC IN PVC CONDUIT",
        },
        # === Power (P) section — 16 circuits → auto-pad to 18 (2 SPAREs) ===
        {
            "name": "1 Nos 13A SINGLE S/S/O + 2 Nos 13A TWIN S/S/O",
            "circuit_id": "L1P1",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A SINGLE S/S/O + 1 Nos 13A TWIN S/S/O",
            "circuit_id": "L2P1",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A SINGLE S/S/O + 1 Nos 13A TWIN S/S/O",
            "circuit_id": "L3P1",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        # === ISOL 1 ===
        {
            "name": "20A DP ISOLATOR",
            "circuit_id": "ISOL1",
            "breaker_type": "ISOLATOR",
            "breaker_rating": 20,
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A SINGLE S/S/O",
            "circuit_id": "L2P2",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A TWIN S/S/O",
            "circuit_id": "L3P2",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos 13A TWIN S/S/O",
            "circuit_id": "L1P3",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A SINGLE S/S/O",
            "circuit_id": "L2P3",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        # === ISOL 2 ===
        {
            "name": "20A DP ISOLATOR",
            "circuit_id": "ISOL2",
            "breaker_type": "ISOLATOR",
            "breaker_rating": 20,
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A TWIN S/S/O",
            "circuit_id": "L1P4",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos 13A TWIN S/S/O",
            "circuit_id": "L2P4",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        # === ISOL 3 ===
        {
            "name": "20A DP ISOLATOR",
            "circuit_id": "ISOL3",
            "breaker_type": "ISOLATOR",
            "breaker_rating": 20,
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos 13A TWIN S/S/O",
            "circuit_id": "L1P5",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "2 Nos 13A TWIN S/S/O",
            "circuit_id": "L2P5",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "1 Nos 13A TWIN S/S/O",
            "circuit_id": "L3P5",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        {
            "name": "4 Nos 13A TWIN S/S/O",
            "circuit_id": "L1P6",
            "breaker_type": "MCB",
            "breaker_rating": 20,
            "breaker_characteristic": "B",
            "cable": "2 x 1C 2.5mm² PVC + 2.5mm² CPC IN PVC CONDUIT",
        },
        # SPAREs auto-generated by _pad_spares_for_triplets()
    ],
}

application_info = {
    "clientName": "ULTIMED HEALTHCARE CLINICS",
    "address": "BLK 824 TAMPINES STREET 81 #01-36",
    "mainContractor": "FIRE SOLUTIONS ENGINEERING PTE LTD",
    "electrical_contractor": "NEWSPACE INTERIOR PTE LTD",
    "contractor_address": "6D MANDAI ESTATE, #09-06 SINGAPORE 729938",
    "drawing_number": "NSI_UHC_TAM_01",
    "sld_only_mode": True,
}

output_dir = os.path.join(os.path.dirname(__file__), "..", "output")
os.makedirs(output_dir, exist_ok=True)

pdf_path = os.path.join(output_dir, "63A_TPN_test.pdf")
svg_path = os.path.join(output_dir, "63A_TPN_test.svg")

generator = SldGenerator()
result = generator.generate(
    requirements=requirements,
    application_info=application_info,
    pdf_output_path=pdf_path,
    svg_output_path=svg_path,
    backend_type="dxf",
)

print(f"PDF: {result['pdf_path']}")
print(f"Components: {result['component_count']}")
print("Done!")
